# This override file should be used when running this service in isolation
# to provide dependencies and expose ports for local testing

services:
  ffc-pay-data-hub:
    build:
      target: development
    image: ffc-pay-data-hub-development
    container_name: ffc-pay-data-hub-development
    ports:
      - "9280:9229"
    volumes:
      - ./app:/home/node/app
      - ./package.json:/home/node/package.json

  ffc-pay-event-store-azurite:
    volumes:
      - azurite_data:/data
    ports:
      - "10070:10000"
      - "10071:10001"
      - "10072:10002"

  ffc-pay-data-hub-redis:
    volumes:
      - redis_data:/data
    ports:
      - "6391:6379"
    command: redis-server --dir /data --save 5 1

volumes:
  azurite_data:
  redis_data:
