environment: production
environmentCode:
name: ffc-pay-data-hub
namespace: ffc-pay
workstream: ffc-pay
image: ffc-pay-data-hub

labels:
  component: service

appInsights:
  connectionString:

containerConfigMap:
  name: ffc-pay-data-hub-config-map

containerSecret:
  name: ffc-pay-data-hub-container-secret
  type: Opaque

deployment:
  minReplicas: 1
  maxReplicas: 4
  cpuThreshold: 70
  memoryThreshold: 70

container:
  requestMemory: 150Mi
  requestCpu: 150m
  limitMemory: 300Mi
  limitCpu: 300m
  messageQueueHost: namespace.servicebus.windows.net
  dataTopicAddress: ffc-pay-data-request
  dataSubscriptionAddress: ffc-pay-data-hub
  dataResponseQueueAddress: ffc-pay-data-request-response
  redisHostname: redis-redis-ha.default
  redisPassword: redis
  redisPort: 6379
  redisPartition: ffc-pay-data-hub
  azureStorageConnectionString: dummy
  azureStorageUseConnectionString: false
  azureStorageAccountName: ffcpay

aadPodIdentity: true

azureIdentity:
  clientID: not-a-real-clientID
  resourceID: not-a-real-resourceID
