environment: production
environmentCode:
name: ffc-pay-data-hub
namespace: ffc-pay
workstream: ffc-pay
image: ffc-pay-data-hub

labels:
  component: service

appInsights:
  key:

containerConfigMap:
  name: ffc-pay-data-hub-config-map

containerSecret:
  name: ffc-pay-data-hub-container-secret
  type: Opaque

deployment: {}

container:
  requestMemory: 100Mi
  requestCpu: 100m
  limitMemory: 100Mi
  limitCpu: 100m
  port: 3009

livenessProbe:
  path: /healthz
  port: 3009
  initialDelaySeconds: 20
  periodSeconds: 10
  failureThreshold: 3
  timeoutSeconds: 5

readinessProbe:
  path: /healthy
  port: 3009
  initialDelaySeconds: 30
  periodSeconds: 10
  failureThreshold: 3
  timeoutSeconds: 5
