#!/usr/bin/env sh

projectRoot="$(a="/$0"; a=${a%/*}; a=${a:-.}; a=${a#/}/; cd "$a/.." || return; pwd)"

service="ffc-pay-data-hub"

cd "${projectRoot}"
  # Create test output folder
  mkdir -p test-output

# Guarantee clean environment
docker-compose -f docker-compose.yaml -f docker-compose.acceptance.yaml -p "${service}-test-runner" down -v

# Ensure container images are up to date
docker-compose -f docker-compose.yaml -f docker-compose.acceptance.yaml -p "${service}-acceptance-test" build

echo "============================================"
echo "Running Pay Data Hub Acceptance Test(s)"
echo "============================================"
# Start container and run tests
docker-compose -f docker-compose.yaml -f docker-compose.acceptance.yaml -p "${service}-acceptance-test" run --rm "${service}-test-runner" ${command}

echo "============================================"
echo "Tear down environment"
echo "============================================"
# Tear down environment
docker-compose -f docker-compose.yaml -f docker-compose.acceptance.yaml -p "${service}-test-runner" down -v
